DROP TABLE IF EXISTS UserSessions;
CREATE TABLE IF NOT EXISTS UserSessions (
  PrivateId TEXT PRIMARY KEY NOT NULL UNIQUE,
  SessionId TEXT NOT NULL UNIQUE,
  UserId TEXT NOT NULL,
  UserAgent TEXT NOT NULL,
  CHECK (LENGTH(SessionId) >= 32) -- 128-bit minimum
);